import { Music } from '@/types/music';

export const musics: Music[] = [
  {
    id: '1',
    title: 'Death Bed',
    artist_name: 'Powfu',
    image_link: 'https://samplesongs.netlify.app/album-arts/death-bed.jpg',
    album_name: 'Poems of the past',
  },
  {
    id: '2',
    title: 'Bad Liar',
    artist_name: 'Imagine Dragons',
    image_link: 'https://samplesongs.netlify.app/album-arts/bad-liar.jpg',
    album_name: 'Origins',
  },
  {
    id: '3',
    title: 'Faded',
    artist_name: 'Alan Walker',
    image_link: 'https://samplesongs.netlify.app/album-arts/faded.jpg',
    album_name: 'Faded (Remixes)',
  },
  {
    id: '4',
    title: 'Hate Me',
    artist_name: 'Ellie Goulding',
    image_link: 'https://samplesongs.netlify.app/album-arts/hate-me.jpg',
    album_name: 'Brightest Blue',
  },
  {
    id: '5',
    title: 'Solo',
    artist_name: 'Clean Bandit',
    image_link: 'https://samplesongs.netlify.app/album-arts/solo.jpg',
    album_name: 'What Is Love?',
  },
  {
    id: '6',
    title: 'Without Me',
    artist_name: 'Halsey',
    image_link: 'https://samplesongs.netlify.app/album-arts/without-me.jpg',
    album_name: 'Manic',
  },
  {
    id: '7',
    title: 'Faded',
    artist_name: 'Alan Walker',
    image_link: 'https://samplesongs.netlify.app/album-arts/faded.jpg',
    album_name: 'Faded (Remixes)',
  },
  {
    id: '8',
    title: 'Hate Me',
    artist_name: 'Ellie Goulding',
    image_link: 'https://samplesongs.netlify.app/album-arts/hate-me.jpg',
    album_name: 'Brightest Blue',
  },
  {
    id: '9',
    title: 'Solo',
    artist_name: 'Clean Bandit',
    image_link: 'https://samplesongs.netlify.app/album-arts/solo.jpg',
    album_name: 'What Is Love?',
  },
  {
    id: '10',
    title: 'Without Me',
    artist_name: 'Halsey',
    image_link: 'https://samplesongs.netlify.app/album-arts/without-me.jpg',
    album_name: 'Manic',
  },
  {
    id: '11',
    title: 'Faded',
    artist_name: 'Alan Walker',
    image_link: 'https://samplesongs.netlify.app/album-arts/faded.jpg',
    album_name: 'Faded (Remixes)',
  },
  {
    id: '12',
    title: 'Hate Me',
    artist_name: 'Ellie Goulding',
    image_link: 'https://samplesongs.netlify.app/album-arts/hate-me.jpg',
    album_name: 'Brightest Blue',
  },
  {
    id: '13',
    title: 'Solo',
    artist_name: 'Clean Bandit',
    image_link: 'https://samplesongs.netlify.app/album-arts/solo.jpg',
    album_name: 'What Is Love?',
  },
  {
    id: '14',
    title: 'Without Me',
    artist_name: 'Halsey',
    image_link: 'https://samplesongs.netlify.app/album-arts/without-me.jpg',
    album_name: 'Manic',
  },
  {
    id: '15',
    title: 'Faded',
    artist_name: 'Alan Walker',
    image_link: 'https://samplesongs.netlify.app/album-arts/faded.jpg',
    album_name: 'Faded (Remixes)',
  },
  {
    id: '16',
    title: 'Hate Me',
    artist_name: 'Ellie Goulding',
    image_link: 'https://samplesongs.netlify.app/album-arts/hate-me.jpg',
    album_name: 'Brightest Blue',
  },
  {
    id: '17',
    title: 'Solo',
    artist_name: 'Clean Bandit',
    image_link: 'https://samplesongs.netlify.app/album-arts/solo.jpg',
    album_name: 'What Is Love?',
  },
  {
    id: '18',
    title: 'Without Me',
    artist_name: 'Halsey',
    image_link: 'https://samplesongs.netlify.app/album-arts/without-me.jpg',
    album_name: 'Manic',
  },
  {
    id: '19',
    title: 'Faded',
    artist_name: 'Alan Walker',
    image_link: 'https://samplesongs.netlify.app/album-arts/faded.jpg',
    album_name: 'Faded (Remixes)',
  },
  {
    id: '20',
    title: 'Hate Me',
    artist_name: 'Ellie Goulding',
    image_link: 'https://samplesongs.netlify.app/album-arts/hate-me.jpg',
    album_name: 'Brightest Blue',
  },
  {
    id: '21',
    title: 'Solo',
    artist_name: 'Clean Bandit',
    image_link: 'https://samplesongs.netlify.app/album-arts/solo.jpg',
    album_name: 'What Is Love?',
  },
  {
    id: '22',
    title: 'Without Me',
    artist_name: 'Halsey',
    image_link: 'https://samplesongs.netlify.app/album-arts/without-me.jpg',
    album_name: 'Manic',
  },
  {
    id: '23',
    title: 'Faded',
    artist_name: 'Alan Walker',
    image_link: 'https://samplesongs.netlify.app/album-arts/faded.jpg',
    album_name: 'Faded (Remixes)',
  },
  {
    id: '24',
    title: 'Hate Me',
    artist_name: 'Ellie Goulding',
    image_link: 'https://samplesongs.netlify.app/album-arts/hate-me.jpg',
    album_name: 'Brightest Blue',
  },
  {
    id: '25',
    title: 'Solo',
    artist_name: 'Clean Bandit',
    image_link: 'https://samplesongs.netlify.app/album-arts/solo.jpg',
    album_name: 'What Is Love?',
  },
  {
    id: '26',
    title: 'Without Me',
    artist_name: 'Halsey',
    image_link: 'https://samplesongs.netlify.app/album-arts/without-me.jpg',
    album_name: 'Manic',
  },
  {
    id: '27',
    title: 'Faded',
    artist_name: 'Alan Walker',
    image_link: 'https://samplesongs.netlify.app/album-arts/faded.jpg',
    album_name: 'Faded (Remixes)',
  },
  {
    id: '28',
    title: 'Hate Me',
    artist_name: 'Ellie Goulding',
    image_link: 'https://samplesongs.netlify.app/album-arts/hate-me.jpg',
    album_name: 'Brightest Blue',
  },
  {
    id: '29',
    title: 'Solo',
    artist_name: 'Clean Bandit',
    image_link: 'https://samplesongs.netlify.app/album-arts/solo.jpg',
    album_name: 'What Is Love?',
  },
  {
    id: '30',
    title: 'Without Me',
    artist_name: 'Halsey',
    image_link: 'https://samplesongs.netlify.app/album-arts/without-me.jpg',
    album_name: 'Manic',
  },
  {
    id: '31',
    title: 'Faded',
    artist_name: 'Alan Walker',
    image_link: 'https://samplesongs.netlify.app/album-arts/faded.jpg',
    album_name: 'Faded (Remixes)',
  },
  {
    id: '32',
    title: 'Hate Me',
    artist_name: 'Ellie Goulding',
    image_link: 'https://samplesongs.netlify.app/album-arts/hate-me.jpg',
    album_name: 'Brightest Blue',
  },
  {
    id: '33',
    title: 'Solo',
    artist_name: 'Clean Bandit',
    image_link: 'https://samplesongs.netlify.app/album-arts/solo.jpg',
    album_name: 'What Is Love?',
  },
  {
    id: '34',
    title: 'Without Me',
    artist_name: 'Halsey',
    image_link: 'https://samplesongs.netlify.app/album-arts/without-me.jpg',
    album_name: 'Manic',
  },
];
