import { Music } from "@/app/types/music";

export const musics: Music[] = [
  {
    title: "Death Bed",
    artist_name: "Powfu",
    image: "https://samplesongs.netlify.app/album-arts/death-bed.jpg",
    album_name: "Poems of the past",
    id: "1",
  },
  {
    title: "Bad Liar",
    artist_name: "Imagine Dragons",
    image: "https://samplesongs.netlify.app/album-arts/bad-liar.jpg",
    album_name: "Origins",
    id: "2",
  },
  {
    title: "Faded",
    artist_name: "Alan Walker",
    image: "https://samplesongs.netlify.app/album-arts/faded.jpg",
    album_name: "Faded (Remixes)",
    id: "3",
  },
  {
    title: "Hate Me",
    artist_name: "Ellie Goulding",
    image: "https://samplesongs.netlify.app/album-arts/hate-me.jpg",
    album_name: "Brightest Blue",
    id: "4",
  },
  {
    title: "Solo",
    artist_name: "Clean Bandit",
    image: "https://samplesongs.netlify.app/album-arts/solo.jpg",
    album_name: "What Is Love?",
    id: "5",
  },
  {
    title: "Without Me",
    artist_name: "Halsey",
    image: "https://samplesongs.netlify.app/album-arts/without-me.jpg",
    album_name: "Manic",
    id: "6",
  },
  {
    title: "Faded",
    artist_name: "Alan Walker",
    image: "https://samplesongs.netlify.app/album-arts/faded.jpg",
    album_name: "Faded (Remixes)",
    id: "7",
  },
  {
    title: "Hate Me",
    artist_name: "Ellie Goulding",
    image: "https://samplesongs.netlify.app/album-arts/hate-me.jpg",
    album_name: "Brightest Blue",
    id: "8",
  },
  {
    title: "Solo",
    artist_name: "Clean Bandit",
    image: "https://samplesongs.netlify.app/album-arts/solo.jpg",
    album_name: "What Is Love?",
    id: "9",
  },
  {
    title: "Without Me",
    artist_name: "Halsey",
    image: "https://samplesongs.netlify.app/album-arts/without-me.jpg",
    album_name: "Manic",
    id: "10",
  },
  {
    title: "Faded",
    artist_name: "Alan Walker",
    image: "https://samplesongs.netlify.app/album-arts/faded.jpg",
    album_name: "Faded (Remixes)",
    id: "11",
  },
  {
    title: "Hate Me",
    artist_name: "Ellie Goulding",
    image: "https://samplesongs.netlify.app/album-arts/hate-me.jpg",
    album_name: "Brightest Blue",
    id: "12",
  },
  {
    title: "Solo",
    artist_name: "Clean Bandit",
    image: "https://samplesongs.netlify.app/album-arts/solo.jpg",
    album_name: "What Is Love?",
    id: "13",
  },
  {
    title: "Without Me",
    artist_name: "Halsey",
    image: "https://samplesongs.netlify.app/album-arts/without-me.jpg",
    album_name: "Manic",
    id: "14",
  },
  {
    title: "Faded",
    artist_name: "Alan Walker",
    image: "https://samplesongs.netlify.app/album-arts/faded.jpg",
    album_name: "Faded (Remixes)",
    id: "15",
  },
  {
    title: "Hate Me",
    artist_name: "Ellie Goulding",
    image: "https://samplesongs.netlify.app/album-arts/hate-me.jpg",
    album_name: "Brightest Blue",
    id: "16",
  },
  {
    title: "Solo",
    artist_name: "Clean Bandit",
    image: "https://samplesongs.netlify.app/album-arts/solo.jpg",
    album_name: "What Is Love?",
    id: "17",
  },
  {
    title: "Without Me",
    artist_name: "Halsey",
    image: "https://samplesongs.netlify.app/album-arts/without-me.jpg",
    album_name: "Manic",
    id: "18",
  },
  {
    title: "Faded",
    artist_name: "Alan Walker",
    image: "https://samplesongs.netlify.app/album-arts/faded.jpg",
    album_name: "Faded (Remixes)",
    id: "19",
  },
  {
    title: "Hate Me",
    artist_name: "Ellie Goulding",
    image: "https://samplesongs.netlify.app/album-arts/hate-me.jpg",
    album_name: "Brightest Blue",
    id: "20",
  },
  {
    title: "Solo",
    artist_name: "Clean Bandit",
    image: "https://samplesongs.netlify.app/album-arts/solo.jpg",
    album_name: "What Is Love?",
    id: "21",
  },
  {
    title: "Without Me",
    artist_name: "Halsey",
    image: "https://samplesongs.netlify.app/album-arts/without-me.jpg",
    album_name: "Manic",
    id: "22",
  },
  {
    title: "Faded",
    artist_name: "Alan Walker",
    image: "https://samplesongs.netlify.app/album-arts/faded.jpg",
    album_name: "Faded (Remixes)",
    id: "23",
  },
  {
    title: "Hate Me",
    artist_name: "Ellie Goulding",
    image: "https://samplesongs.netlify.app/album-arts/hate-me.jpg",
    album_name: "Brightest Blue",
    id: "24",
  },
  {
    title: "Solo",
    artist_name: "Clean Bandit",
    image: "https://samplesongs.netlify.app/album-arts/solo.jpg",
    album_name: "What Is Love?",
    id: "25",
  },
  {
    title: "Without Me",
    artist_name: "Halsey",
    image: "https://samplesongs.netlify.app/album-arts/without-me.jpg",
    album_name: "Manic",
    id: "26",
  },
  {
    title: "Faded",
    artist_name: "Alan Walker",
    image: "https://samplesongs.netlify.app/album-arts/faded.jpg",
    album_name: "Faded (Remixes)",
    id: "27",
  },
  {
    title: "Hate Me",
    artist_name: "Ellie Goulding",
    image: "https://samplesongs.netlify.app/album-arts/hate-me.jpg",
    album_name: "Brightest Blue",
    id: "28",
  },
  {
    title: "Solo",
    artist_name: "Clean Bandit",
    image: "https://samplesongs.netlify.app/album-arts/solo.jpg",
    album_name: "What Is Love?",
    id: "29",
  },
  {
    title: "Without Me",
    artist_name: "Halsey",
    image: "https://samplesongs.netlify.app/album-arts/without-me.jpg",
    album_name: "Manic",
    id: "30",
  },
  {
    title: "Faded",
    artist_name: "Alan Walker",
    image: "https://samplesongs.netlify.app/album-arts/faded.jpg",
    album_name: "Faded (Remixes)",
    id: "31",
  },
  {
    title: "Hate Me",
    artist_name: "Ellie Goulding",
    image: "https://samplesongs.netlify.app/album-arts/hate-me.jpg",
    album_name: "Brightest Blue",
    id: "32",
  },
  {
    title: "Solo",
    artist_name: "Clean Bandit",
    image: "https://samplesongs.netlify.app/album-arts/solo.jpg",
    album_name: "What Is Love?",
    id: "33",
  },
  {
    title: "Without Me",
    artist_name: "Halsey",
    image: "https://samplesongs.netlify.app/album-arts/without-me.jpg",
    album_name: "Manic",
    id: "34",
  },
];
